<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="MarshPanel_V1" duration-ms="36375" started-at="2020-04-13T00:11:33 IST" finished-at="2020-04-13T00:12:09 IST">
    <groups>
    </groups>
    <test name="MarshPanel Test" duration-ms="36375" started-at="2020-04-13T00:11:33 IST" finished-at="2020-04-13T00:12:09 IST">
      <class name="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP">
        <test-method status="PASS" signature="forgotpassword1()[pri:0, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@1f7030a6]" name="forgotpassword1" duration-ms="15942" started-at="2020-04-13T00:11:33 IST" description="Click PROCEED button with email id blank" finished-at="2020-04-13T00:11:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword1 -->
        <test-method status="PASS" signature="forgotpassword2()[pri:0, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@1f7030a6]" name="forgotpassword2" duration-ms="2558" started-at="2020-04-13T00:11:49 IST" description="Click PROCEED button with incorrect Email format" finished-at="2020-04-13T00:11:52 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword2 -->
        <test-method status="FAIL" signature="forgotpassword3()[pri:0, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@1f7030a6]" name="forgotpassword3" duration-ms="6039" started-at="2020-04-13T00:11:52 IST" description="Click PROCEED button with wrong email id" finished-at="2020-04-13T00:11:58 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP.forgotpassword3(TC_ForgotPassword_002_OTP.java:112)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword3 -->
        <test-method status="PASS" signature="forgotpassword4()[pri:0, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@1f7030a6]" name="forgotpassword4" duration-ms="5583" started-at="2020-04-13T00:11:58 IST" description="Click PROCEED button with Valid Employee Details" finished-at="2020-04-13T00:12:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword4 -->
        <test-method status="PASS" signature="forgotpassword5()[pri:0, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@1f7030a6]" name="forgotpassword5" duration-ms="161" started-at="2020-04-13T00:12:04 IST" description="Verify User information" finished-at="2020-04-13T00:12:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword5 -->
        <test-method status="PASS" signature="forgotpassword6()[pri:0, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@1f7030a6]" name="forgotpassword6" duration-ms="5793" started-at="2020-04-13T00:12:04 IST" description="Click Generate OTP button without click checkbox" finished-at="2020-04-13T00:12:09 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword6 -->
      </class> <!-- com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP -->
    </test> <!-- MarshPanel Test -->
  </suite> <!-- MarshPanel_V1 -->
</testng-results>
