<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="13" passed="11">
  <reporter-output>
  </reporter-output>
  <suite name="MarshPanel_V1" duration-ms="64303" started-at="2020-04-13T22:21:32 IST" finished-at="2020-04-13T22:22:36 IST">
    <groups>
    </groups>
    <test name="MarshPanel Test" duration-ms="64303" started-at="2020-04-13T22:21:32 IST" finished-at="2020-04-13T22:22:36 IST">
      <class name="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP">
        <test-method status="PASS" signature="forgotpassword0()[pri:1, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@396f6598]" name="forgotpassword0" duration-ms="16710" started-at="2020-04-13T22:21:32 IST" description="Click forgot password link" finished-at="2020-04-13T22:21:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword0 -->
        <test-method status="PASS" signature="forgotpassword1()[pri:2, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@396f6598]" name="forgotpassword1" duration-ms="406" started-at="2020-04-13T22:21:49 IST" description="Click PROCEED button with email id blank" finished-at="2020-04-13T22:21:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword1 -->
        <test-method status="PASS" signature="forgotpassword2()[pri:3, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@396f6598]" name="forgotpassword2" duration-ms="2663" started-at="2020-04-13T22:21:49 IST" description="Click PROCEED button with incorrect Email format" finished-at="2020-04-13T22:21:52 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword2 -->
        <test-method status="FAIL" signature="forgotpassword3()[pri:4, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@396f6598]" name="forgotpassword3" duration-ms="5302" started-at="2020-04-13T22:21:52 IST" description="Click PROCEED button with wrong email id" finished-at="2020-04-13T22:21:57 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP.forgotpassword3(TC_ForgotPassword_002_OTP.java:118)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword3 -->
        <test-method status="PASS" signature="forgotpassword4()[pri:5, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@396f6598]" name="forgotpassword4" duration-ms="5462" started-at="2020-04-13T22:21:57 IST" description="Click PROCEED button with Valid Employee Details" finished-at="2020-04-13T22:22:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword4 -->
        <test-method status="PASS" signature="forgotpassword5()[pri:6, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@396f6598]" name="forgotpassword5" duration-ms="133" started-at="2020-04-13T22:22:03 IST" description="Verify User information" finished-at="2020-04-13T22:22:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword5 -->
        <test-method status="PASS" signature="forgotpassword6()[pri:7, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@396f6598]" name="forgotpassword6" duration-ms="4953" started-at="2020-04-13T22:22:03 IST" description="Click Generate OTP button without click checkbox" finished-at="2020-04-13T22:22:08 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword6 -->
        <test-method status="PASS" signature="forgotpassword7()[pri:8, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@396f6598]" name="forgotpassword7" duration-ms="2625" started-at="2020-04-13T22:22:08 IST" description="Click Submit button option without entered OTP" finished-at="2020-04-13T22:22:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword7 -->
        <test-method status="PASS" signature="forgotpassword8()[pri:9, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@396f6598]" name="forgotpassword8" duration-ms="4915" started-at="2020-04-13T22:22:10 IST" description="Click Submit button option without entered new password" finished-at="2020-04-13T22:22:15 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword8 -->
        <test-method status="PASS" signature="forgotpassword9()[pri:10, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@396f6598]" name="forgotpassword9" duration-ms="4949" started-at="2020-04-13T22:22:15 IST" description="Click Submit button option without entered Confirm Password" finished-at="2020-04-13T22:22:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword9 -->
        <test-method status="PASS" signature="forgotpassword10()[pri:11, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@396f6598]" name="forgotpassword10" duration-ms="4884" started-at="2020-04-13T22:22:20 IST" description="Click Submit button option with diff new and confirm password" finished-at="2020-04-13T22:22:25 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword10 -->
        <test-method status="PASS" signature="forgotpassword11()[pri:12, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@396f6598]" name="forgotpassword11" duration-ms="5277" started-at="2020-04-13T22:22:25 IST" description="Click Submit button option with invalid OTP" finished-at="2020-04-13T22:22:30 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword11 -->
        <test-method status="FAIL" signature="forgotpassword12()[pri:13, instance:com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP@396f6598]" name="forgotpassword12" duration-ms="5686" started-at="2020-04-13T22:22:30 IST" description="Click Submit button option With valid OTP and password Details" finished-at="2020-04-13T22:22:36 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP.forgotpassword12(TC_ForgotPassword_002_OTP.java:352)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpassword12 -->
      </class> <!-- com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP -->
    </test> <!-- MarshPanel Test -->
  </suite> <!-- MarshPanel_V1 -->
</testng-results>
